FROM consol/debian-xfce-vnc

USER 0

RUN apt-get update && apt-get install -y openssh-server sudo btop \
    && mkdir -p /var/run/sshd \
    && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config \
    && useradd -m -s /bin/bash user \
    && echo "user:user" | chpasswd \
    && usermod -aG sudo user \
    && echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 22 5901
