services:
  debian-xfce-vnc:
    build:
      context: .
      dockerfile: Dockerfile.debian-xfce-vnc
    container_name: debian-xfce-vnc
    environment:
      VNC_RESOLUTION: "1280x720"
      VNC_COL_DEPTH: "24"
      VNC_QUALITY: "6"
      USER: user
      PASSWORD: vncpassword
    ports:
      - "5900:5901"
      - "10800:10800"
      - "4096:4096"
    restart: unless-stopped
    cpus: '2'
    mem_limit: 4g
    mem_reservation: 2g
    networks:
      - kooterm-net

  kooterm:
    build: .
    container_name: kooterm
    depends_on:
      - debian-xfce-vnc
    ports:
      - "53001:3001"
      - "53443:3443"
    environment:
      LOG_LEVEL: debug
      VNC_ENABLE: "true"
      TARGET_HOST: debian-xfce-vnc
      VNC_PORT: "5901"
      SSH_PORT: "22"
      SSH_USER: user
      SSH_PASS: user
    restart: unless-stopped
    cpus: '0.5'
    mem_limit: 1g
    mem_reservation: 512m
    networks:
      - kooterm-net

networks:
  kooterm-net:
    driver: bridge
